language: python
python:
  - "3.8"

services:
  - docker

install:
  - pip install -r requirements.txt

script:
  docker-compose run linting
  docker-compose run python_test

after_success:
  - codecov