language: python
python:
  - "3.8"

env:
  - DOCKER_COMPOSE_VERSION=1.29.2

services:
  - docker

install:
  - pip install -r requirements.txt

script:
  - docker-compose run linting
  - docker-compose run python_test

after_success:
  - codecov